name: iPod
packages:
  SwiftUIPager:
    url: https://github.com/fermoya/SwiftUIPager
    from: 2.5.0
targets:
  iPod:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [iPod, Resources]
    dependencies:
      - package: SwiftUIPager
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.AppInstalleriOS.SwiftUIPager
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
